/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenAPI specification */
        get: operations["getOpenApi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List markets */
        get: operations["listMarkets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/{market}/orderbook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get market orderbook snapshot */
        get: operations["getOrderBook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orders */
        get: operations["listOrders"];
        put?: never;
        /** Submit an order */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/{market}/funding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get latest funding state */
        get: operations["getFundingState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/{market}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get perpetual positions for a market */
        get: operations["getPositions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MessageResponse: {
            data: string;
        };
        ErrorResponse: {
            error: string;
        };
        Market: {
            symbol: string;
            market_type: string;
            base_asset: string;
            quote_asset: string;
        };
        /** @enum {string} */
        OrderSide: "buy" | "sell";
        /** @enum {string} */
        OrderType: "market" | "limit";
        OrderInput: {
            market: string;
            side: components["schemas"]["OrderSide"];
            order_type: components["schemas"]["OrderType"];
            /** Format: float */
            size: number;
            /** Format: float */
            price?: number | null;
            reduce_only: boolean;
            account: string;
        };
        Order: {
            id: string;
            status: string;
            market: string;
            side: components["schemas"]["OrderSide"];
            order_type: components["schemas"]["OrderType"];
            /** Format: float */
            size: number;
            /** Format: float */
            price?: number | null;
            reduce_only: boolean;
            account: string;
            /** Format: int64 */
            created_at_ms: number;
        };
        OrderLevel: {
            /** Format: float */
            price: number;
            /** Format: float */
            size: number;
        };
        OrderBook: {
            market: string;
            bids: components["schemas"]["OrderLevel"][];
            asks: components["schemas"]["OrderLevel"][];
            /** Format: int64 */
            updated_at_ms: number;
        };
        PerpetualPosition: {
            market: string;
            account: string;
            /** Format: float */
            size: number;
            /** Format: float */
            entry_price: number;
            /** Format: float */
            unrealized_pnl: number;
            /** Format: float */
            margin_used: number;
            /** Format: float */
            mark_price: number;
        };
        FundingState: {
            market: string;
            /** Format: float */
            current_funding_rate: number;
            /** Format: int64 */
            next_funding_interval_ms: number;
        };
        MarketListResponse: {
            data: components["schemas"]["Market"][];
        };
        OrderListResponse: {
            data: components["schemas"]["Order"][];
        };
        OrderResponse: {
            data: components["schemas"]["Order"];
        };
        OrderBookResponse: {
            data: components["schemas"]["OrderBook"];
        };
        PositionsResponse: {
            data: components["schemas"]["PerpetualPosition"][];
        };
        FundingResponse: {
            data: components["schemas"]["FundingState"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is running */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
        };
    };
    getOpenApi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listMarkets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Market list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketListResponse"];
                };
            };
        };
    };
    getOrderBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current orderbook */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderBookResponse"];
                };
            };
            /** @description Market not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listOrders: {
        parameters: {
            query?: {
                market?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponse"];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderInput"];
            };
        };
        responses: {
            /** @description Order accepted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Invalid order payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getFundingState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Funding snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundingResponse"];
                };
            };
            /** @description Funding not available */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPositions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Positions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionsResponse"];
                };
            };
        };
    };
}
